=== 007multy/BFHRGP_XMLGyak/XMLTaskBFHRGP/XMLSchemaBFHRGP.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cukraszdak">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cukraszda">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cukraszda_adatok" type="cukraszdaTipus" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="futar" type="futarTipus" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="termek" type="termekTipus" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="vevo" type="vevoTipus" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded" minOccurs="0" />
							<xs:element name="kartya" type="kartyaTipus" maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

		<xs:key name="CukraszdaID">
			<xs:selector xpath="cukraszda/cukraszda_adatok"/>
			<xs:field xpath="@CukraszdaID"/>
		</xs:key>

		<xs:key name="FutarID">
			<xs:selector xpath="cukraszda/futar"/>
			<xs:field xpath="@FutarID"/>
		</xs:key>

		<xs:key name="TermekID">
			<xs:selector xpath="cukraszda/termek"/>
			<xs:field xpath="@TermekID"/>
		</xs:key>
		
		<xs:key name="VevoID">
			<xs:selector xpath="cukraszda/vevo"/>
			<xs:field xpath="@VevoID"/>
		</xs:key>
		
		<xs:key name="RendelesID">
			<xs:selector xpath="cukraszda/rendeles"/>
			<xs:field xpath="@RendelesID"/>
		</xs:key>

		<xs:key name="Kartyaszam">
			<xs:selector xpath="cukraszda/kartya"/>
			<xs:field xpath="@Kartyaszam"/>
		</xs:key>
		
		<xs:keyref name="cukraszda-futar" refer="CukraszdaID">
			<xs:selector xpath="cukraszda/futar/CukraszdaID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		
		<xs:keyref name="cukraszda-termek" refer="CukraszdaID">
			<xs:selector xpath="cukraszda/termek/CukraszdaID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		
		<xs:keyref name="termek-rendeles" refer="TermekID">
			<xs:selector xpath="cukraszda/rendeles/TermekID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		
		<xs:keyref name="vevo-rendeles" refer="VevoID">
			<xs:selector xpath="cukraszda/rendeles/VevoID"/>
			<xs:field xpath="."/>
		</xs:keyref>
		
		<xs:keyref name="vevo-kartya" refer="VevoID">
			<xs:selector xpath="cukraszda/kartya/VevoID"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>

	<xs:complexType name="cukraszdaTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="nev" />
			<xs:element type="xs:string" name="nyitvatartas" />
			<xs:element type="xs:string" name="weboldal"/>
			<xs:element type="xs:int" name="telefonszam"/>	
		</xs:sequence>
		<xs:attribute type="xs:short" name="CukraszdaID" use="required" />
	</xs:complexType>

	<xs:complexType name="futarTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="nev" />
			<xs:element type="xs:string" name="telefonszam" />
			<xs:element type="xs:short"  name="CukraszdaID" />
		</xs:sequence>
		<xs:attribute type="xs:short" name="FutarID" use="required" />
	</xs:complexType>

	<xs:complexType name="termekTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="nev" />
			<xs:element type="xs:string" name="tipus" />
			<xs:element type="xs:int" name="egyseg_ar" />
			<xs:element type="xs:short"  name="CukraszdaID" />
		</xs:sequence>
		<xs:attribute type="xs:short" name="TermekID" use="required" />
	</xs:complexType>

	<xs:complexType name="vevoTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="nev" />
			<xs:element type="xs:short" name="iranyitoszam" />
			<xs:element type="xs:string" name="varos" />
			<xs:element type="xs:string" name="utca" />
			<xs:element type="xs:short" name="hazszam" />
			<xs:element type="xs:long" name="telefonszam" />
		</xs:sequence>
		<xs:attribute type="xs:short" name="VevoID" use="required" />
	</xs:complexType>
	
	<xs:complexType name="rendelesTipus">
		<xs:sequence>
			<xs:element type="xs:int" name="mennyiseg" />
			<xs:element type="xs:int" name="fizetendo_osszeg" />
			<xs:element type="xs:short" name="TermekID" />
			<xs:element type="xs:short" name="VevoID" />
		</xs:sequence>
		<xs:attribute type="xs:short" name="RendelesID" use="required" />
	</xs:complexType>
		
	<xs:complexType name="kartyaTipus">
		<xs:sequence>
			<xs:element type="xs:string" name="tipus" />
			<xs:element type="xs:date" name="lejarati_datum" />
			<xs:element type="xs:string" name="bank" />
			<xs:element type="xs:short"  name="VevoID" />
		</xs:sequence>
		<xs:attribute type="xs:long" name="Kartyaszam" use="required" />
	</xs:complexType>
</xs:schema>

=== 007multy/BFHRGP_XMLGyak/XMLTaskBFHRGP/XMLBFHRGP.xml
<?xml version="1.0" encoding="UTF-8"?>
<cukraszdak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaBFHRGP.xsd">
	<cukraszda>
		<cukraszda_adatok CukraszdaID="1">
			<nev>Stühmer cukrászda</nev>
			<nyitvatartas>10:00-17:00</nyitvatartas>
			<weboldal>stuhmer.hu</weboldal>
			<telefonszam>0636517372</telefonszam>
		</cukraszda_adatok>

		<futar FutarID="1">
			<nev>Kis Béla</nev>
			<telefonszam>06301234567</telefonszam>
			<CukraszdaID>1</CukraszdaID>
		</futar>
		<futar FutarID="2">
			<nev>Nagy Béla</nev>
			<telefonszam>06707654321</telefonszam>
			<CukraszdaID>1</CukraszdaID>
		</futar>

		<termek TermekID="1">
			<nev>Melódia</nev>
			<tipus>szelet</tipus>
			<egyseg_ar>500</egyseg_ar>
			<CukraszdaID>1</CukraszdaID>
		</termek>
		<termek TermekID="2">
			<nev>Korfu</nev>
			<tipus>szelet</tipus>
			<egyseg_ar>450</egyseg_ar>
			<CukraszdaID>1</CukraszdaID>
		</termek>
		<termek TermekID="3">
			<nev>Sós-mogyorós barack zsúr</nev>
			<tipus>torta</tipus>
			<egyseg_ar>4500</egyseg_ar>
			<CukraszdaID>1</CukraszdaID>
		</termek>

		<vevo VevoID="1">
			<nev>Nagy Béla</nev>
			<iranyitoszam>3300</iranyitoszam>
			<varos>Eger</varos>
			<utca>Merengő</utca>
			<hazszam>1</hazszam>
			<telefonszam>06309876532</telefonszam>
		</vevo>
		<vevo VevoID="2">
			<nev>Nagy János</nev>			
			<iranyitoszam>3535</iranyitoszam>
			<varos>Miskolc</varos>
			<utca>Eper</utca>
			<hazszam>2</hazszam>		
			<telefonszam>06608884441</telefonszam>
		</vevo>

		<rendeles RendelesID="1">
			<mennyiseg>2</mennyiseg>
			<fizetendo_osszeg>1000</fizetendo_osszeg>
			<TermekID>1</TermekID>
			<VevoID>1</VevoID>
		</rendeles>

		<rendeles RendelesID="2">
			<mennyiseg>1</mennyiseg>
			<fizetendo_osszeg>4500</fizetendo_osszeg>
			<TermekID>3</TermekID>
			<VevoID>2</VevoID>
		</rendeles>

		<rendeles RendelesID="3">
			<mennyiseg>3</mennyiseg>
			<fizetendo_osszeg>1350</fizetendo_osszeg>
			<TermekID>2</TermekID>
			<VevoID>1</VevoID>
		</rendeles>

		<kartya Kartyaszam="1177339100111222">
			<tipus>SZÉP</tipus>
			<lejarati_datum>2022-11-30</lejarati_datum>
			<bank>OTP</bank>
			<VevoID>1</VevoID>
		</kartya>
		<kartya Kartyaszam="117733901234567">
			<tipus>Bank</tipus>
			<lejarati_datum>2023-05-02</lejarati_datum>
			<bank>MKB</bank>
			<VevoID>1</VevoID>
		</kartya>
		<kartya Kartyaszam="8823569123547632">
			<tipus>SZÉP</tipus>
			<lejarati_datum>2021-12-31</lejarati_datum>
			<bank>KH</bank>
			<VevoID>2</VevoID>
		</kartya>
	</cukraszda>
</cukraszdak>
